# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: myprtfl's Projects
email: myprtfl@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  myprtfl's Projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://myprtfl.github.io/about/" # the base hostname & protocol for your site
# twitter_username: myprtfl
github_username:  myprtfl
# twitter_username: jekyllrb

# Build settings
markdown: kramdown

repository: 'git@github.com:/myprtfl/myprtfl.github.io.git'

# Serving
detach:  false
port:    8080
host:    0.0.0.0
baseurl: "" # does not include hostname